### ISSUE TITLE
no rich presence on linux

### ISSUE THREAD

**Issue by ghost** [vanishedvan/aseprite-rich-presence#4]
i'm running this on fedora 32, x64, kernel 5.9.11-100.fc32.x86_64

i went through the install instructions, set the path in the config file, generated a client id, and ran the node app. everything opens and runs fine, but discord doesn't actually show any rich presence; it's no different from running aseprite normally

```
$ aseprite --version
Aseprite 1.x-dev
```

built from the aseprite master branch, commit c0ac9208ff281c567a22f18d8312915f01337d1d

**Comment by ibrahimcaj** [comment]
You don't need to change the client ID. That is probably why the presence isn't showing.

**Comment by ghost** [comment]
> You don't need to change the client ID. That is probably why the presence isn't showing.

i only changed it after the default id didn't do anything
